version: '3'

services:
  web:
    build: .
    command: carton exec starman -I/carton/lib/perl5 -Ilib -e 'enable ForceEnv => REMOTE_USER => $ENV{EMAIL}' app_ibis.psgi
    volumes:
      - .:/code
      - carton:/carton
      - vendor:/vendor
    networks:
      - web
    ports:
      - "5000:5000"

networks:
  web:

volumes:
  carton:
  vendor:
