version: "3"

services:
  web:
    build:
      network: host
      context: .
    command: carton exec starman -I/carton/lib/perl5 -Ilib -e 'enable ForceEnv => REMOTE_USER => $$ENV{EMAIL}' app_ibis.psgi
    # command: carton exec plackup -I/carton/lib/perl5 -Ilib -e 'enable ForceEnv => REMOTE_USER => $$ENV{EMAIL}' app_ibis.psgi
    # command: cat app_ibis.conf
    volumes:
      # - .:/code
      - carton:/carton
      - vendor:/vendor
    networks:
      - web
    ports:
      - "5000:5000"
    environment:
      CATALYST_DEBUG: 1
      PERL_CARTON_PATH: /carton
      PERL5LIB: /code/lib:/carton/lib/perl5
      EMAIL: test@lol.biz

networks:
  web:

volumes:
  carton:
  vendor:
