#!/bin/bash

ROOT=${ROOT:=.}
GITHUB=https://raw.githubusercontent.com/doriantaylor

pushd $ROOT/root/asset

[ -f rdfa.xsl ] || curl -o rdfa.xsl $GITHUB/xslt-rdfa/master/rdfa.xsl
[ -f transclude.xsl ] || curl -o transclude.xsl $GITHUB/xslt-transclusion/master/transclude.xsl

popd
